<?php
/**
 * Lithuanian panel strings — fall through to English for any missing key via array merge in i18n.
 * Full machine pack is generated by scripts/finish-langs.py / generate-langs-mymemory.py when available.
 */
declare(strict_types=1);

$base = require __DIR__ . '/panel-en.php';
$lt = [
    'panel_dashboard' => 'Skydelis',
    'panel_websites' => 'Svetainės',
    'panel_files' => 'Failų tvarkyklė',
    'panel_account' => 'Paskyra',
    'panel_logout' => 'Atsijungti',
    'panel_installer' => 'Programų diegimas',
    'btn_save' => 'Išsaugoti',
    'btn_cancel' => 'Atšaukti',
    'btn_add' => 'Pridėti',
    'btn_delete' => 'Ištrinti',
    'btn_edit' => 'Redaguoti',
    'nav_menu' => 'Meniu',
    'domains_subdomains' => 'Subdomenai',
];
return array_replace($base, $lt);
